-- Registration form controls and canonical Iranian city data. Hidden fields
-- retain their historical values; only active requirements participate in
-- dossier validation.

alter table public.site_settings
  add column if not exists member_education_enabled boolean not null default true,
  add column if not exists member_field_of_study_enabled boolean not null default true;

create table if not exists public.iran_cities (
  id bigint generated by default as identity primary key,
  province text not null,
  name text not null,
  sort_order integer not null default 0,
  constraint iran_cities_province_name_key unique (province, name)
);

with source(province, cities) as (values
  ('آذربایجان شرقی','تبریز،مراغه،مرند،میانه،اهر،بناب،سراب،آذرشهر،اسکو،شبستر،هشترود،جلفا،کلیبر،ملکان،بستان‌آباد'),
  ('آذربایجان غربی','ارومیه،خوی،میاندوآب،مهاباد،بوکان،سلماس،نقده،پیرانشهر،سردشت،شاهین‌دژ،ماکو،اشنویه،تکاب،چایپاره،شوط،پلدشت'),
  ('اردبیل','اردبیل،پارس‌آباد،مشگین‌شهر،خلخال،گرمی،بیله‌سوار،نمین،نیر،کوثر،اصلاندوز،سرعین'),
  ('اصفهان','اصفهان،کاشان،خمینی‌شهر،نجف‌آباد،شاهین‌شهر،شهرضا،فلاورجان،مبارکه،زرین‌شهر،آران و بیدگل،گلپایگان،فریدون‌شهر،نطنز،سمیرم،خوانسار،اردستان،نائین'),
  ('البرز','کرج،فردیس،نظرآباد،هشتگرد،محمدشهر،اشتهارد،کمال‌شهر،ماهدشت،طالقان،چهارباغ'),
  ('ایلام','ایلام،دهلران،ایوان،آبدانان،دره‌شهر،مهران،سرابله،بدره،چرداول،ملکشاهی'),
  ('بوشهر','بوشهر،برازجان،گناوه،کنگان،خورموج،جم،دیر،دیلم،عسلویه،اهرم،دلوار'),
  ('تهران','تهران،شهریار،اسلامشهر،قدس،ملارد،پاکدشت،قرچک،ورامین،رباط کریم،پرند،پردیس،دماوند،فیروزکوه،ری،شمیرانات،بومهن'),
  ('چهارمحال و بختیاری','شهرکرد،بروجن،فارسان،لردگان،فرخ‌شهر،سامان،اردل،بن،کیان،کوهرنگ،خانمیرزا'),
  ('خراسان جنوبی','بیرجند،قائن،طبس،فردوس،نهبندان،سربیشه،بشرویه،خوسف،درمیان،سرایان،زیرکوه'),
  ('خراسان رضوی','مشهد،نیشابور،سبزوار،تربت حیدریه،کاشمر،قوچان،تربت جام،تایباد،چناران،گناباد،سرخس،خواف،درگز،فریمان،بردسکن،طرقبه،شاندیز،فیروزه'),
  ('خراسان شمالی','بجنورد،شیروان،اسفراین،آشخانه،جاجرم،گرمه،فاروج،راز،مانه،سملقان'),
  ('خوزستان','اهواز،آبادان،خرمشهر،دزفول،اندیمشک،ماهشهر،بهبهان،شوشتر،مسجدسلیمان،ایذه،رامهرمز،شوش،شادگان،سوسنگرد،هندیجان،باغ‌ملک،امیدیه،رامشیر'),
  ('زنجان','زنجان،ابهر،خرمدره،قیدار،سلطانیه،آب‌بر،ماه‌نشان،زرین‌آباد،ایجرود،طارم'),
  ('سمنان','سمنان،شاهرود،دامغان،گرمسار،مهدی‌شهر،سرخه،آرادان،میامی،ایوانکی'),
  ('سیستان و بلوچستان','زاهدان،زابل،ایرانشهر،چابهار،خاش،سراوان،کنارک،نیک‌شهر،زهک،هیرمند،دلگان،قصرقند،راسک،سیب و سوران،مهرستان،میرجاوه'),
  ('فارس','شیراز،مرودشت،جهرم،کازرون،فسا،داراب،لار،فیروزآباد،آباده،اقلید،نی‌ریز،نورآباد،لامرد،استهبان،سپیدان،قیر،خنج،زرقان،گراش'),
  ('قزوین','قزوین،تاکستان،الوند،آبیک،بوئین‌زهرا،محمدیه،اقبالیه،آوج،شال،ضیاءآباد'),
  ('قم','قم،جعفریه،کهک،قنوات،دستجرد،سلفچگان'),
  ('کردستان','سنندج،سقز،مریوان،بانه،قروه،کامیاران،بیجار،دیواندره،دهگلان،سروآباد'),
  ('کرمان','کرمان،سیرجان،رفسنجان،جیرفت،بم،زرند،کهنوج،بافت،بردسیر،شهربابک،عنبرآباد،منوجان،راور،رودبار جنوب،فهرج،ریگان'),
  ('کرمانشاه','کرمانشاه،اسلام‌آباد غرب،جوانرود،کنگاور،سنقر،سرپل ذهاب،پاوه،صحنه،هرسین،گیلانغرب،قصر شیرین،روانسر،ثلاث باباجانی'),
  ('کهگیلویه و بویراحمد','یاسوج،دهدشت،دوگنبدان،لیکک،سی‌سخت،چرام،باشت،لنده،مارگون'),
  ('گلستان','گرگان،گنبد کاووس،علی‌آباد کتول،بندر ترکمن،آق‌قلا،کردکوی،مینودشت،کلاله،آزادشهر،رامیان،گمیشان،گالیکش،بندر گز'),
  ('گیلان','رشت،بندر انزلی،لاهیجان،لنگرود،تالش،آستارا،رودسر،صومعه‌سرا،فومن،رودبار،آستانه اشرفیه،رضوانشهر،ماسال،شفت،سیاهکل'),
  ('لرستان','خرم‌آباد،بروجرد،دورود،کوهدشت،الیگودرز،نورآباد،ازنا،پلدختر،الشتر،چگنی،رومشکان'),
  ('مازندران','ساری،بابل،آمل،قائم‌شهر،بهشهر،نکا،بابلسر،چالوس،تنکابن،نوشهر،رامسر،جویبار،محمودآباد،نور،فریدونکنار،کلاردشت،عباس‌آباد،گلوگاه'),
  ('مرکزی','اراک،ساوه،خمین،محلات،دلیجان،تفرش،شازند،آشتیان،کمیجان،زرندیه،خنداب،فراهان'),
  ('هرمزگان','بندرعباس،میناب،قشم،بندر لنگه،کیش،رودان،حاجی‌آباد،جاسک،بستک،پارسیان،خمیر،سیریک،ابوموسی'),
  ('همدان','همدان،ملایر،نهاوند،تویسرکان،کبودرآهنگ،اسدآباد،بهار،رزن،لالجین،فامنین،درگزین'),
  ('یزد','یزد،میبد،اردکان،بافق،مهریز،ابرکوه،تفت،اشکذر،زارچ،بهاباد،خاتم،مروست')
), expanded as (
  select source.province, trim(city.name) as name, city.ordinality::integer as sort_order
  from source
  cross join lateral unnest(string_to_array(source.cities, '،')) with ordinality as city(name, ordinality)
)
insert into public.iran_cities(province, name, sort_order)
select province, name, sort_order from expanded
on conflict (province, name) do update set sort_order=excluded.sort_order;

alter table public.iran_cities enable row level security;
drop policy if exists iran_cities_read on public.iran_cities;
create policy iran_cities_read on public.iran_cities for select to authenticated using (true);
grant select on public.iran_cities to authenticated;
grant usage, select on sequence public.iran_cities_id_seq to authenticated;

create or replace function public.validate_team_people_before_payment()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_person public.team_members%rowtype;
begin
  if new.lifecycle_status in (
       'awaiting_review',
       'awaiting_payment',
       'payment_pending',
       'payment_submitted',
       'registered'
     )
     and old.lifecycle_status is distinct from new.lifecycle_status then
    if nullif(trim(coalesce(new.province, '')), '') is null
       or nullif(trim(coalesce(new.city, '')), '') is null then
      raise exception 'team_location_required';
    end if;
    for v_person in
      select * from public.team_members where team_id = new.id
    loop
      if not public._team_person_complete_for_league(v_person, new.league_id) then
        raise exception 'team_dossier_incomplete:member_identity';
      end if;
    end loop;
  end if;
  return new;
end;
$$;

create or replace function public._team_person_complete_for_league(
  p_member public.team_members,
  p_league_id uuid
)
returns boolean language sql stable set search_path=public as $$
  select
    nullif(trim(coalesce(p_member.first_name_fa,'')),'') is not null
    and nullif(trim(coalesce(p_member.last_name_fa,'')),'') is not null
    and nullif(trim(coalesce(p_member.first_name_en,'')),'') is not null
    and nullif(trim(coalesce(p_member.last_name_en,'')),'') is not null
    and nullif(trim(coalesce(p_member.father_name_fa,'')),'') is not null
    and nullif(trim(coalesce(p_member.father_name_en,'')),'') is not null
    and p_member.birth_date is not null
    and nullif(trim(coalesce(p_member.role,'')),'') is not null
    and nullif(trim(coalesce(p_member.residence,'')),'') is not null
    and nullif(trim(coalesce(p_member.country_code,'')),'') is not null
    and nullif(trim(coalesce(p_member.nationality,'')),'') is not null
    and (
      not coalesce((select member_education_enabled from public.site_settings where id=1), true)
      or nullif(trim(coalesce(p_member.education_level,'')),'') is not null
    )
    and (not exists(select 1 from public.registration_doc_types where scope='member' and code='member_photo' and is_active and is_required)
      or nullif(trim(coalesce(p_member.photo_url,'')),'') is not null)
    and (not exists(select 1 from public.registration_doc_types where scope='member' and code='member_identity' and is_active and is_required)
      or nullif(trim(coalesce(p_member.national_id_doc_path,'')),'') is not null)
    and (coalesce(p_member.is_foreign,false) or p_member.national_id ~ '^[0-9]{10}$')
    and (not coalesce(p_member.is_foreign,false) or nullif(trim(coalesce(p_member.passport_number,'')),'') is not null)
    and (p_member.role not in ('captain','coach') or p_member.phone ~ '^09[0-9]{9}$')
    and (p_member.role <> 'member' or not exists(
      select 1 from public.leagues l where l.id=p_league_id and (
        (l.min_age is not null and extract(year from age(current_date,p_member.birth_date)) < l.min_age)
        or (l.max_age is not null and extract(year from age(current_date,p_member.birth_date)) > l.max_age)
      )
    ))
$$;
