-- Keep every public information page represented in the CMS. Public pages
-- consume these rows when populated, so content is not split silently between
-- hardcoded React copy and the admin editor.
insert into public.static_pages(slug,title,title_en,excerpt,excerpt_en,body,body_en)
values
('about','درباره ما','About us','معرفی جام تبرستان','About Tabarestan Cup','<h2>جام تبرستان</h2><p>جام تبرستان بستری حرفه‌ای برای رقابت، یادگیری و دیده‌شدن استعدادهای رباتیک، مکاترونیک و هوش مصنوعی است.</p><h2>ماموریت و چشم‌انداز</h2><p>هدف ما برگزاری رقابت‌های شفاف و استاندارد، رشد مهارت‌های فنی و ساختن مسیر پایدار از تجربه نخست تا فعالیت حرفه‌ای است.</p><h2>حوزه‌های فعالیت</h2><ul><li>رباتیک و مکاترونیک</li><li>هوش مصنوعی و سامانه‌های هوشمند</li><li>مسابقات حرفه‌ای و داوری تخصصی</li></ul>','<h2>Tabarestan Cup</h2><p>Tabarestan Cup is a professional platform for competition, learning and recognition across robotics, mechatronics and artificial intelligence.</p><h2>Mission and vision</h2><p>We create transparent, rigorous competitions that turn technical knowledge into practical capability and professional opportunity.</p>'),
('contact','تماس با ما','Contact us','راه‌های ارتباط با دبیرخانه','Contact the secretariat','<h2>ارتباط با دبیرخانه</h2><p>برای پرسش‌های مربوط به ثبت‌نام، لیگ‌ها و پشتیبانی از راه‌های ارتباطی درج‌شده در همین صفحه استفاده کنید.</p>','<h2>Contact the secretariat</h2><p>For registration, league and support questions, use the contact channels shown on this page.</p>'),
('faq','سوالات متداول','Frequently asked questions','پاسخ پرسش‌های پرتکرار','Answers to common questions','<h2>ثبت‌نام چگونه انجام می‌شود؟</h2><p>پس از ورود یا ساخت حساب، اطلاعات هویتی و تیم را تکمیل کنید، مدارک را بارگذاری و مراحل بررسی، پذیرش قوانین و پرداخت را انجام دهید.</p><h2>آیا اعضای تیم حساب جداگانه دارند؟</h2><p>خیر. اعضا به‌عنوان افراد وابسته به تیم ثبت می‌شوند و حساب CRM مستقل ندارند.</p><h2>برای پشتیبانی چه کار کنم؟</h2><p>از صفحه تماس با ما پیام ارسال کنید یا از شماره و ایمیل دبیرخانه استفاده کنید.</p>','<h2>How does registration work?</h2><p>Create or sign in to your account, complete identity and team information, upload documents, accept the rules and pay.</p><h2>Do team members need separate accounts?</h2><p>No. Team members are stored as people belonging to the team and do not receive separate CRM accounts.</p>'),
('registration-guide','راهنمای ثبت‌نام','Registration guide','مراحل ثبت‌نام و پرداخت','Registration and payment steps','<h2>مراحل ثبت‌نام</h2><ol><li>ورود یا ساخت حساب و تأیید شماره موبایل</li><li>تکمیل اطلاعات هویتی و نوع شرکت‌کننده</li><li>انتخاب لیگ، ساخت تیم و افزودن اعضا</li><li>بازبینی اطلاعات و بارگذاری مدارک فعال</li><li>ارسال مستندات فنی، پذیرش قوانین و پرداخت</li><li>دریافت مجوز حضور پس از تأیید پرداخت</li></ol><p>سرپرست، مربی و اعضا افراد وابسته به تیم هستند و حساب CRM جداگانه دریافت نمی‌کنند.</p>','<h2>Registration steps</h2><ol><li>Sign in or create an account and verify your mobile number.</li><li>Complete identity and participant information.</li><li>Select a league, create a team and add its people.</li><li>Review information and upload active required documents.</li><li>Submit technical files, accept the rules and pay.</li><li>Receive attendance clearance after payment approval.</li></ol><p>Captains, coaches and members belong to the team and do not receive separate CRM accounts.</p>'),
('privacy','حریم خصوصی','Privacy policy','حفاظت از اطلاعات کاربران','Protection of participant information','','')
on conflict (slug) do update set
  title = case when nullif(trim(public.static_pages.title),'') is null then excluded.title else public.static_pages.title end,
  title_en = case when nullif(trim(public.static_pages.title_en),'') is null then excluded.title_en else public.static_pages.title_en end,
  excerpt = case when nullif(trim(public.static_pages.excerpt),'') is null then excluded.excerpt else public.static_pages.excerpt end,
  excerpt_en = case when nullif(trim(public.static_pages.excerpt_en),'') is null then excluded.excerpt_en else public.static_pages.excerpt_en end,
  body = case when nullif(trim(public.static_pages.body),'') is null then excluded.body else public.static_pages.body end,
  body_en = case when nullif(trim(public.static_pages.body_en),'') is null then excluded.body_en else public.static_pages.body_en end;
