import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { formatAppDate } from '@/lib/dates'
import { sanitizeHtml } from '@/lib/sanitize'

type Props = { kind: 'article' | 'announcement'; title: string; excerpt?: string | null; body: string; coverImage?: string | null; coverAlt?: string | null; author?: string | null; publishedAt?: string | null; category?: string | null; backTo: string; backLabel: string }
const plainText = (html: string) => html.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim()

export function ArticleDetail(props: Props) {
  props = { ...props, body: sanitizeHtml(props.body) }
  const { i18n } = useTranslation()
  const isEn = i18n.language.startsWith('en')
  const [copied, setCopied] = useState(false)
  const minutes = Math.max(1, Math.ceil(plainText(props.body).split(' ').filter(Boolean).length / (isEn ? 220 : 180)))
  const published = props.publishedAt ? formatAppDate(props.publishedAt, i18n.language) : ''
  const articleType = props.kind === 'announcement' ? (isEn ? 'Official announcement' : 'اطلاعیه رسمی') : (isEn ? 'Article' : 'مقاله')
  const schema = useMemo(() => ({ '@context': 'https://schema.org', '@type': props.kind === 'announcement' ? 'NewsArticle' : 'Article', headline: props.title, description: props.excerpt || plainText(props.body).slice(0, 160), image: props.coverImage || undefined, datePublished: props.publishedAt || undefined, author: { '@type': 'Person', name: props.author || (isEn ? 'Tabarestan Cup editorial team' : 'تحریریه جام تبرستان') }, mainEntityOfPage: typeof window === 'undefined' ? undefined : window.location.href }), [props, isEn])
  useEffect(() => { const script = document.createElement('script'); script.type = 'application/ld+json'; script.textContent = JSON.stringify(schema); document.head.appendChild(script); return () => script.remove() }, [schema])
  const share = async () => { if (navigator.share) await navigator.share({ title: props.title, url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } }

  return <article className="pb-16">
    <header className="relative overflow-hidden border-b border-sky-100 bg-gradient-to-br from-sky-50 via-white to-emerald-50 px-4 pb-16 pt-14"><span className="absolute -end-28 -top-28 size-80 rounded-full border-[55px] border-sky-100/60" aria-hidden="true" /><div className="relative mx-auto max-w-4xl text-center"><div className="flex flex-wrap items-center justify-center gap-2 text-xs font-black"><span className="rounded-full bg-sky-700 px-3 py-1.5 text-white">{articleType}</span>{props.category ? <span className="rounded-full bg-white px-3 py-1.5 text-emerald-800 ring-1 ring-emerald-200">{props.category}</span> : null}</div><h1 className="mx-auto mt-6 max-w-3xl text-3xl font-black leading-[1.5] text-slate-950 sm:text-5xl sm:leading-[1.35]">{props.title}</h1>{props.excerpt ? <p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">{props.excerpt}</p> : null}<div className="mt-7 flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-xs font-bold text-slate-600"><span>{isEn ? 'By' : 'نویسنده'}: <strong className="text-slate-900">{props.author || (isEn ? 'Tabarestan Cup editorial team' : 'تحریریه جام تبرستان')}</strong></span>{published ? <time>{published}</time> : null}<span>{minutes.toLocaleString(isEn ? 'en-US' : 'fa-IR')} {isEn ? 'min read' : 'دقیقه مطالعه'}</span><button type="button" onClick={() => void share()} className="rounded-xl bg-white px-3 py-2 text-sky-700 shadow-sm ring-1 ring-sky-100 transition hover:-translate-y-0.5">{copied ? (isEn ? 'Link copied' : 'لینک کپی شد') : (isEn ? 'Share' : 'اشتراک‌گذاری')}</button></div></div></header>
    <div className="mx-auto -mt-8 max-w-5xl px-4">{props.coverImage ? <figure className="relative overflow-hidden rounded-[2rem] border-4 border-white bg-slate-100 shadow-[0_25px_70px_rgb(18_76_98/0.16)]"><img src={props.coverImage} alt={props.coverAlt || props.title} className="aspect-[16/8] w-full object-cover" /></figure> : null}<div className="mx-auto mt-10 max-w-3xl rounded-[2rem] border border-sky-100 bg-white px-5 py-8 shadow-[0_18px_55px_rgb(18_76_98/0.07)] sm:px-10 sm:py-12"><div className="article-content break-words text-[1.04rem] leading-9 text-slate-700 [&_a]:font-bold [&_a]:text-sky-700 [&_a]:underline [&_blockquote]:my-7 [&_blockquote]:rounded-e-2xl [&_blockquote]:border-s-4 [&_blockquote]:border-emerald-500 [&_blockquote]:bg-emerald-50 [&_blockquote]:p-5 [&_h2]:mb-4 [&_h2]:mt-10 [&_h2]:text-2xl [&_h2]:font-black [&_h2]:text-slate-950 [&_h3]:mb-3 [&_h3]:mt-8 [&_h3]:text-xl [&_h3]:font-black [&_h3]:text-slate-900 [&_img]:my-7 [&_img]:h-auto [&_img]:max-w-full [&_img]:rounded-2xl [&_li]:mb-2 [&_ol]:my-5 [&_ol]:list-decimal [&_ol]:ps-6 [&_p]:my-5 [&_strong]:text-slate-950 [&_table]:block [&_table]:max-w-full [&_table]:overflow-x-auto [&_ul]:my-5 [&_ul]:list-disc [&_ul]:ps-6" dangerouslySetInnerHTML={{ __html: props.body }} /><aside className="mt-12 rounded-2xl bg-gradient-to-l from-sky-700 to-emerald-600 p-6 text-white"><h2 className="text-lg font-black">{isEn ? 'Ready to join the competition?' : 'برای حضور در مسابقات آماده‌اید؟'}</h2><p className="mt-2 text-sm leading-7 text-white/85">{isEn ? 'Explore active leagues and review their registration requirements.' : 'لیگ‌های فعال را ببینید و شرایط ثبت‌نام هر مسابقه را بررسی کنید.'}</p><Link to="/leagues" className="mt-4 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-black text-sky-800">{isEn ? 'View active leagues' : 'مشاهده لیگ‌های فعال'}</Link></aside><Link to={props.backTo} className="mt-8 inline-flex text-sm font-black text-sky-700 hover:underline">{props.backLabel}</Link></div></div>
  </article>
}
