import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { PanelPage } from '@/components/layout/PanelShell'
import { Button, Textarea } from '@/components/ui/FormControls'
import { useToast } from '@/components/ui/Toast'
import { fetchTeamById } from '@/features/registration/api'
import { acceptAttendanceRules, fetchAttendance, submitTechnical, technicalSignedUrl, uploadTechnicalFile, type AttendanceClearance, type AttendanceSettings, type TechnicalFile } from '@/features/attendance/api'
import type { Team, TeamMember } from '@/types/database'
import { formatAppDateTime } from '@/lib/dates'

const steps=[['members','اعضا و تیم'],['technical','مدارک فنی'],['rules','قوانین حضور'],['confirmed','مجوز حضور']] as const

export function TeamAttendancePage(){
  const {teamId=''}=useParams(); const {i18n}=useTranslation(); const fa=!i18n.language.startsWith('en'); const toast=useToast()
  const [team,setTeam]=useState<Team|null>(null),[flow,setFlow]=useState<AttendanceClearance|null>(null),[settings,setSettings]=useState<AttendanceSettings|null>(null)
  const [members,setMembers]=useState<TeamMember[]>([]),[files,setFiles]=useState<TechnicalFile[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[accepted,setAccepted]=useState(false)
  const load=useCallback(async()=>{setError('');try{const nextTeam=await fetchTeamById(teamId);if(!nextTeam)throw new Error('team_not_found');setTeam(nextTeam);const data=await fetchAttendance(teamId,nextTeam.league_id);setFlow(data.flow);setSettings(data.settings);setMembers(data.members);setFiles(data.files);setNote(data.flow.participant_note??'')}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اطلاعات')}},[teamId])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(flow?.stage==='confirmed')return;const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[flow?.stage,load])
  const stageIndex=Math.max(0,steps.findIndex(([key])=>key===flow?.stage)); const allMembersApproved=members.length>0&&members.every(m=>m.review_status==='approved')
  const fileMap=useMemo(()=>Object.fromEntries(files.map(file=>[file.kind,file])),[files]) as Partial<Record<'article'|'robot_video',TechnicalFile>>
  const upload=async(kind:'article'|'robot_video',file?:File)=>{if(!file||!settings)return;setBusy(kind);try{const max=kind==='article'?settings.article_max_bytes:settings.video_max_bytes;const previous=files.find(item=>item.kind===kind)?.file_path;const saved=await uploadTechnicalFile(teamId,kind,file,max,previous);setFiles(current=>[...current.filter(x=>x.kind!==kind),saved]);toast.success(fa?'فایل با موفقیت بارگذاری شد.':'File uploaded successfully.')}catch(e){toast.error(e instanceof Error&&e.message==='file_too_large'?(fa?'حجم فایل از محدودیت تعیین‌شده بیشتر است.':'The file exceeds the configured size limit.'):(fa?'نوع فایل یا محتوای آن مجاز نیست.':'The file type or content is not allowed.'))}finally{setBusy('')}}
  if(error)return <PanelPage index="AT.01" title={fa?'مجوز حضور در مسابقات':'Competition clearance'}><div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-800">{error}<Button type="button" className="mt-4" onClick={()=>void load()}>{fa?'تلاش مجدد':'Retry'}</Button></div></PanelPage>
  if(!team||!flow||!settings)return <PanelPage index="AT.01" title={fa?'مجوز حضور در مسابقات':'Competition clearance'}><p className="text-sm text-slate-500">{fa?'در حال بارگذاری…':'Loading…'}</p></PanelPage>
  return <PanelPage index="AT.01" title={fa?'مجوز حضور در مسابقات':'Competition clearance'} description={`${team.name} · ${fa?'فرآیند پس از پرداخت و احراز صلاحیت حضور':'Post-payment attendance verification'}`}>
    <div className="mb-6 overflow-x-auto pb-2"><ol className="flex min-w-[620px] items-start">{steps.map(([key,label],index)=><li key={key} className="relative flex flex-1 flex-col items-center text-center before:absolute before:start-0 before:top-5 before:h-0.5 before:w-full before:bg-slate-200 first:before:w-1/2 first:before:start-1/2 last:before:w-1/2"><span className={`relative z-10 grid size-10 place-items-center rounded-full border-4 border-white text-sm font-black shadow-sm ${index<stageIndex?'bg-emerald-600 text-white':index===stageIndex?'bg-amber-500 text-white':'bg-slate-200 text-slate-500'}`}>{index<stageIndex?'✓':index+1}</span><strong className={`mt-2 text-xs ${index===stageIndex?'text-slate-900':'text-slate-500'}`}>{fa?label:['Members','Technical files','Rules','Clearance'][index]}</strong></li>)}</ol></div>
    {flow.stage==='members'?<section className="rounded-3xl border border-amber-200 bg-white p-5 shadow-sm sm:p-7"><StateIcon tone="amber" icon="⌛"/><h2 className="text-center text-xl font-black text-slate-900">{fa?settings.member_review_title_fa:settings.member_review_title_en}</h2><p className="mx-auto mt-3 max-w-2xl text-center text-sm leading-7 text-slate-600">{fa?settings.member_review_help_fa:settings.member_review_help_en}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{members.map(member=><MemberState key={member.id} member={member} teamId={teamId} fa={fa}/>)}</div>{allMembersApproved&&team.status!=='approved'?<p className="mt-5 rounded-xl bg-amber-50 p-3 text-center text-sm font-bold text-amber-800">{fa?'اعضا تأیید شده‌اند و تأیید نهایی تیم در انتظار کمیته فنی است.':'Members are approved; final team approval is pending.'}</p>:null}</section>:null}
    {flow.stage==='technical'?<section className="rounded-3xl border border-sky-200 bg-white p-5 shadow-sm sm:p-7"><StateIcon tone={flow.technical_status==='rejected'?'rose':'amber'} icon={flow.technical_status==='pending'?'⌛':'⇧'}/><h2 className="text-center text-xl font-black text-slate-900">{fa?'ارسال مقاله و فیلم ربات':'Robot paper and video'}</h2><p className="mx-auto mt-3 max-w-2xl text-center text-sm leading-7 text-slate-600">{fa?settings.technical_help_fa:settings.technical_help_en}</p>{flow.technical_rejection_reason?<p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><strong>{fa?'دلیل عدم تأیید: ':'Rejection reason: '}</strong>{flow.technical_rejection_reason}</p>:null}<div className="mt-6 grid gap-4 md:grid-cols-2"><FileUploader kind="article" title={fa?'مقاله ربات':'Robot paper'} hint={fa?'PDF یا Word، حداکثر ۹۰ مگابایت':'PDF or Word, up to 90 MB'} accept=".pdf,.docx" file={fileMap.article} busy={busy==='article'} locked={flow.technical_status==='pending'} onFile={file=>void upload('article',file)}/><FileUploader kind="robot_video" title={fa?'فیلم ربات':'Robot video'} hint={fa?'MP4، WebM یا MOV، حداکثر ۹۰ مگابایت':'MP4, WebM or MOV, up to 90 MB'} accept="video/mp4,video/webm,video/quicktime" file={fileMap.robot_video} busy={busy==='robot_video'} locked={flow.technical_status==='pending'} onFile={file=>void upload('robot_video',file)}/></div>{flow.technical_status==='pending'?<div className="mt-6 rounded-2xl bg-amber-50 p-5 text-center text-sm font-bold text-amber-800"><span className="mx-auto mb-3 block size-7 animate-spin rounded-full border-4 border-amber-200 border-t-amber-600"/>{fa?'مدارک برای کمیته فنی ارسال شده و در حال بررسی است.':'The technical committee is reviewing your files.'}</div>:<Button type="button" className="mt-6 w-full sm:w-auto" disabled={busy!==''||(!fileMap.article&&settings.article_required)||(!fileMap.robot_video&&settings.video_required)} onClick={async()=>{setBusy('submit');try{setFlow(await submitTechnical(teamId));toast.success(fa?'برای بررسی ارسال شد.':'Submitted for review.')}catch(e){toast.error(e instanceof Error?e.message:'خطا')}finally{setBusy('')}}}>{fa?'ارسال جهت بررسی':'Submit for review'}</Button>}</section>:null}
    {flow.stage==='rules'?<section className="rounded-3xl border border-emerald-200 bg-white p-5 shadow-sm sm:p-7"><StateIcon tone="emerald" icon="✓"/><h2 className="text-center text-xl font-black text-slate-900">{fa?settings.rules_title_fa:settings.rules_title_en}</h2><div className="mx-auto mt-5 max-w-3xl whitespace-pre-wrap rounded-2xl bg-slate-50 p-5 text-sm leading-8 text-slate-700">{fa?settings.rules_body_fa:settings.rules_body_en}</div>{settings.participant_note_enabled?<Textarea className="mt-5" label={fa?settings.participant_note_label_fa:settings.participant_note_label_en} value={note} maxLength={3000} onChange={e=>setNote(e.target.value)}/>:null}<label className="mt-5 flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold text-slate-700"><input type="checkbox" className="mt-1 size-5 accent-emerald-600" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>{fa?'قوانین را خوانده‌ام، می‌پذیرم و صحت اطلاعات ثبت‌شده را تأیید می‌کنم.':'I have read and accept the rules and confirm the submitted information.'}</span></label><Button type="button" className="mt-5" disabled={!accepted||busy!==''} onClick={async()=>{setBusy('rules');try{setFlow(await acceptAttendanceRules(teamId,note));toast.success(fa?'مجوز حضور صادر شد.':'Attendance confirmed.')}catch(e){toast.error(e instanceof Error?e.message:'خطا')}finally{setBusy('')}}}>{fa?'تأیید نهایی و دریافت مجوز':'Confirm and receive clearance'}</Button></section>:null}
    {flow.stage==='confirmed'?<section className="overflow-hidden rounded-3xl border border-emerald-200 bg-white shadow-sm"><div className="bg-emerald-600 p-7 text-center text-white"><StateIcon tone="white" icon="✓"/><h2 className="text-2xl font-black">{fa?settings.confirmation_title_fa:settings.confirmation_title_en}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-white/85">{fa?settings.confirmation_message_fa:settings.confirmation_message_en}</p></div><dl className="grid gap-4 p-6 sm:grid-cols-2"><Info label={fa?'محل برگزاری':'Venue'} value={fa?settings.venue_fa:settings.venue_en}/><Info label={fa?'زمان دقیق':'Date and time'} value={formatAppDateTime(settings.event_starts_at,i18n.language)}/><Info label={fa?'نشانی':'Address'} value={fa?settings.venue_address_fa:settings.venue_address_en}/><Info label={fa?'پشتیبانی':'Support'} value={settings.support_phone}/></dl></section>:null}
    <div className="mt-5"><Link to={`/team/${teamId}`} className="text-sm font-black text-sky-700 hover:underline">{fa?'بازگشت به پرونده تیم':'Back to team dossier'}</Link></div>
  </PanelPage>
}

function StateIcon({tone,icon}:{tone:'amber'|'rose'|'emerald'|'white';icon:string}){const cls={amber:'bg-amber-100 text-amber-700',rose:'bg-rose-100 text-rose-700',emerald:'bg-emerald-100 text-emerald-700',white:'bg-white/20 text-white'}[tone];return <span className={`mx-auto mb-4 grid size-16 place-items-center rounded-full text-2xl font-black ${cls}`}>{icon}</span>}
function MemberState({member,teamId,fa}:{member:TeamMember;teamId:string;fa:boolean}){const approved=member.review_status==='approved',rejected=member.review_status==='rejected';const name=`${member.first_name_fa??member.first_name??''} ${member.last_name_fa??member.last_name??''}`.trim()||member.full_name;return <article className={`rounded-2xl border p-4 ${approved?'border-emerald-200 bg-emerald-50/50':rejected?'border-rose-200 bg-rose-50/50':'border-amber-200 bg-amber-50/50'}`}><div className="flex items-center gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full font-black text-white ${approved?'bg-emerald-600':rejected?'bg-rose-600':'bg-amber-500'}`}>{approved?'✓':rejected?'!':'…'}</span><div className="min-w-0"><strong className="block truncate text-sm text-slate-900">{name}</strong><span className="text-xs text-slate-500">{member.role==='captain'?(fa?'سرپرست':'Captain'):member.role==='coach'?(fa?'مربی':'Coach'):(fa?'عضو':'Member')}</span></div>{rejected?<Link to={`/team/${teamId}?editMember=${member.id}`} className="ms-auto rounded-lg bg-rose-600 px-3 py-2 text-xs font-black text-white">{fa?'ویرایش':'Edit'}</Link>:null}</div>{rejected&&member.rejection_reason?<p className="mt-3 border-t border-rose-200 pt-3 text-xs leading-6 text-rose-800">{member.rejection_reason}</p>:null}</article>}
function FileUploader({title,hint,accept,file,busy,locked,onFile}:{kind:string;title:string;hint:string;accept:string;file?:TechnicalFile;busy:boolean;locked:boolean;onFile:(file?:File)=>void}){const [url,setUrl]=useState('');const filePath=file?.file_path;useEffect(()=>{if(filePath)void technicalSignedUrl(filePath).then(setUrl).catch(()=>setUrl(''));else setUrl('')},[filePath]);return <div className="rounded-2xl border border-dashed border-sky-200 bg-sky-50/40 p-4"><div className="flex min-h-36 flex-col items-center justify-center text-center">{busy?<><span className="size-9 animate-spin rounded-full border-4 border-sky-100 border-t-sky-600"/><strong className="mt-3 text-sm text-sky-800">در حال بارگذاری…</strong></>:file?<><span className="grid size-12 place-items-center rounded-xl bg-emerald-100 text-xl text-emerald-700">✓</span><strong className="mt-3 max-w-full truncate text-sm text-slate-800">{file.original_name}</strong><span className="mt-1 text-xs text-slate-500">{(file.size_bytes/1048576).toLocaleString('fa-IR',{maximumFractionDigits:1})} MB</span>{url?<a href={url} target="_blank" rel="noreferrer" className="mt-2 text-xs font-black text-sky-700">مشاهده فایل</a>:null}</>:<><span className="grid size-12 place-items-center rounded-xl bg-white text-xl text-sky-700 shadow-sm">⇧</span><strong className="mt-3 text-sm text-slate-800">{title}</strong><span className="mt-1 text-xs text-slate-500">{hint}</span></>}</div><label className={`mt-3 flex min-h-11 items-center justify-center rounded-xl px-4 text-sm font-black ${locked?'cursor-not-allowed bg-slate-200 text-slate-400':'cursor-pointer bg-sky-600 text-white hover:bg-sky-700'}`}>{file?'جایگزینی فایل':'انتخاب فایل'}<input type="file" className="sr-only" accept={accept} disabled={locked||busy} onChange={e=>onFile(e.target.files?.[0])}/></label></div>}
function Info({label,value}:{label:string;value?:string|null}){return <div className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs font-bold text-slate-400">{label}</dt><dd className="mt-2 text-sm font-black text-slate-800">{value||'—'}</dd></div>}
